### ISSUE TITLE
Create a process to manually test on Windows OS

### ISSUE THREAD

**Issue by biancadanforth** [gregglind/template-shield-study#11] opened 2017-10-13 21:27 UTC
A follow on to [this comment](https://github.com/mozilla/shield-studies-addon-utils/issues/93#issuecomment-336557704); since we want to make sure to check how the studies are displayed/behave in all OSes before launching, we should have a documented process for Windows, as currently only Mac is supported (and Ubuntu, by just updating the `FIREFOX_BINARY` path for the `npm run firefox` script).

Currently for Windows, if trying to do a manual test via `npm run firefox`, neither `npm run build` (making the XPI with a shell script) nor `node manual_test.js` work. The most time-consuming part, as outlined below, is that `manual_test.js` doesn't work (this would automate steps 2-7).

The current brute-force process for Windows:
1. Send yourself an XPI from Mac/Linux to Windows
2. Open a new profile in the appropriate version(s) of Firefox in Windows
  * Note: creating and switching to a new profile may require additional steps: first, create a new profile in `about:profiles`, then make it default, then open it in a new window.
3. Go to about:config and update the two prefs: `extensions.legacy.enabled` and `xpi.signatures.required`
4. Load the temporary addon in `about:debugging` with the XPI
5. Update any study-specific prefs in `about:config` as needed to test a particular behavior/UI.
5. To inspect chrome level elements: Open DevTools, click on "Settings", under "Advanced Settings", check two boxes: `enable browser chrome and addon debugging toolboxes` and `enable remote debugging`
6. Hope you can figure out what changes to make using DevTools
7. Make those changes on your Mac, remake the XPI, and start back at step 1.

Possible solutions:
* Ideally, we could both build the xpi and run `manual_test.js` using selenium webdriver to automate a bunch of this process, as we have done in Mac. This means having the `npm run firefox` command work in Windows.
* We could scale this back by just trying to focus on getting `manual_test.js` to work, and keep sending ourselves the XPIs from the Mac/Linux OS.

**Comment by gregglind** [comment] 2017-10-13 21:47
Claim:  `run_firefox.js` should JUST WORK on windows with node installed.

If we are going this far, then it might be worth getting build to work.

I claim that both of these assume:
- `npm` on windows
- `bash for windows`.  

Testing the failure:

- npm install
- then node
```
require("geckodriver");
const firefox = require("selenium-webdriver/firefox");
const FxRunnerUtils = require("fx-runner/lib/utils");

// check some values of 'binary' like 'firefox' 'nightly' 'beta'
FxRunnerUtils.normalizeBinary(binary).then(console.log);
```

**Comment by biancadanforth** [comment] 2017-10-20 03:36
Unfortunately `run_firefox.js` does not just work.

Things I discovered:
1. `export` in the `firefox` script in `package.json` needs to be replaced with `set`
2. The `zip` command does not exist natively on Windows. It can be installed via [this process](https://ranxing.wordpress.com/2016/12/13/add-zip-into-git-bash-on-windows/).

Here's the error I get now:

```shell
zip I/O error: No such file or directory
zip error: Could not create output file (../dist/@template-shield-study.mozilla.com-1.2.0.xpi)
```

Going to stop here for now. Let me know if you have any other thoughts.

**Comment by gregglind** [comment] 2017-10-20 03:39
I like this bug a lot.  Those both seem fixable.  I can change them to cli
arguments.

Zip and other Unix bits... we can find npm node replacements

**Comment by gregglind** [comment] 2017-10-20 23:55
Based on the testing today, which showed that in GIT BASH scripts run correctly, but when invoked from `npm run-script`, I believe the issue is this:  https://github.com/npm/npm/issues/9420

The solution seems to be to explicitly involve bash where needed, which is.... ugly.  

Ideas and insights welcome, but this is starting to look like a 'can't fix' unless we get rid of all the exports.

**Comment by hoosteeno** [comment] 2017-10-25 19:45
I have successfully run `npm run firefox` and `npm run build` on (a virtualbox) Windows 10 using the Windows Subsystem for Linux. That environment takes a little setup, but once built it required only a modified FIREFOX_BINARY environment variable to make `npm run firefox` work. 

Is this new information? 
Is Win10 an acceptable dependency? 
Would it be helpful for me to document this? Suggested locations?

**Comment by gregglind** [comment] 2017-10-25 21:00
That is new information.  So GIT BASH is NOT GOOD ENOUGH, however the windows subsystem is?  some docs (here, saying how to get the thing, what needs change) is plenty.

**Comment by hoosteeno** [comment] 2017-10-25 21:21
Great.

1. With Windows 10, you can install the Windows subsystem for linux. [These instructions are the clearest, I think](https://hackernoon.com/running-nodejs-on-linux-on-windows-88bd12993bae), but [here are the official steps](https://answers.microsoft.com/en-us/insider/wiki/insider_wintp-insider_install/how-to-enable-the-windows-subsystem-for-linux/16e8f2e8-4a6a-4325-a89a-fd28c7841775?auth=1).

2. The hackernoon instructions above conclude with a node installation, once you've got WSL going. You'll need node:
```
install node curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
sudo apt-get install -y nodejs
```

3. You'll want to update npm: `npm install npm@latest -g`

4. You'll want git and zip, and now since you're using bash on ubuntu, it all works as expected:
```
sudo apt install git
sudo apt install zip
```

5. Now you can follow the standard instructions in the README at [https://github.com/gregglind/template-shield-study](https://github.com/gregglind/template-shield-study) for cloning the repo, installing npm modules and running npm scripts.

Addenda: 
* In your bash environment you may wish to `export FIREFOX_BINARY="/mnt/c/Program Files (x86)/Firefox Developer Edition/firefox.exe"` or similar.
* If you need to access your bash home directory from a Windows explorer or similar (for example, when manually loading the xpi in Firefox), look for it in `%USERPROFILE%\AppData\Local\Lxss\home`
* If you use VisualStudio Code, you can launch that bash environment in its built-in terminal by changing the `terminal.integrated.shell.windows` to `C:\\Windows\\System32\\bash.exe`.
* Notwithstanding the incremental success this approach affords, I have not succeeded in running `npm run test` in this environment. It fails with a 'profile cannot be loaded' error.

**Comment by biancadanforth** [comment] 2017-11-08 04:26
Thanks @hoosteeno for detailing these steps!

I installed the Linux Subsystem on my Windows machine (accessed from the command prompt with the `bash` command), exported the `FIREFOX_BINARY` and ran `npm run firefox`, though I received an [error](https://pastebin.com/Gg28ujn6) related to the fact that this subsystem does not generate certain network metadata correctly.

Did you not get an error to this effect? Apparently this is a [known issue](https://github.com/Microsoft/WSL/issues/1343) in my version of Windows (Version 10.0.14393) that has been fixed on an Insider Build (Version 10.0.14986), and if I apply a ["shim"](https://github.com/Microsoft/WSL/issues/1343#issuecomment-279781472) (just naively replaces the method with an empty method), I get another, [different error](https://pastebin.com/MrMphAED).

**Comment by biancadanforth** [comment] 2017-11-08 16:07
@hoosteeno , What version of Windows 10 do you have? Did you run into any of these bugs? ^

**Comment by gregglind** [comment] 2017-11-08 16:13
Claim:
- this rev / spike has gone as far as it can.
- neither of you are 'windows first devs'
- let's write this up, and get it into some docs in the template.

Closing this, writing up as:  http://github.com/mozilla/shield-studies-addon-template/issues/29

**Closed by gregglind** 2017-11-08 16:13 UTC

**Comment by hoosteeno** [comment] 2017-11-08 16:24
> Closing this,
Agree.

> @hoosteeno , What version of Windows 10 do you have? Did you run into any of these bugs? ^
I'm on Version 10.0.15063, which is probably why I didn't encounter the bug. Will note in http://github.com/mozilla/shield-studies-addon-template/issues/29.
